baseurl = "https://mosajjal.gitlab.io/n0p-blog"
languageCode = "en-us"
theme = "terminal"
paginate = 10

[params]
  contentTypeName = "post"
  themeColor = "blue"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false
  images = ["n0p-blog/img/author.jpg"]

[languages]
  [languages.en]
    title = "n0p blog"
    subtitle = "Ali Mosajjal's Blog"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "n0p"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
