baseURL = "https://blog.n0p.me/"
languageCode = "en"                                      # website language
defaultContentLanguage = "en"                            # [en, zh, ...] determines which i18n file to use
title = "n0p Blog"                                   # website title
theme = "LoveIt"                                         # theme
enableGitInfo = false                                    # whether to use git commit log to generate lastmod record
hasCJKLanguage = false                                   # whether to include chinese/japanese/korean
paginate = 12                                            # default amount of posts in each pages
enableEmoji = true                                       # whether to use emoji code
enableRobotsTXT = true                                   # whether to use robots.txt
googleAnalytics = "UA-114664513-1"                                     # [UA-XXXXXXXX-X] google analytics code
disqusShortname = "n0p-me"                             # Disqus shortname to use Disqus in posts
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
                                                         # copyright description used only for seo schema

                                                      #### Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

staticDir = ["static", "../assets/others"]               # static directories

[author]                                              #### Author Info
  name = "Ali Mosajjal"

[sitemap]                                             #### Sitemap Info
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]                                          #### Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
  posts = ":year/:month/:filename"

[menu]                                                #### Menu Info
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "posts"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "categories"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "tags"
    weight = 2

  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "about"
  #   weight = 4

  # [[menu.main]]
  #   identifier = "zh"
  #   name = '<i class="fas fa-language fa-fw"></i>'
  #   url = "https://hugo-loveit-zh.netlify.com"
  #   weight = 5

[params]
  version = "0.2.X"                                        # LoveIt theme version
  description = "n0p Blog"                      # site description
  images = ["author.jpg"]
  keywords = ["Infosec", "Blue Team", "Linux"]                   # site keywords


  socialShare = true                                     # whether to show social share links in post page

                                                      #### Footer CopyRight Info
  since = 2020                                           # Site creation time
  icp = ''                                               # ICP info only in China (HTML format is allowed)
  # license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
                                                         # license info (HTML format is allowed)
  gitRepo = ""                                           # public git repo url to link lastmod git commit only then enableGitInfo is true

  linkToMarkdown = true                                  # whether to show link to Raw Markdown content of the post

                                                      #### site verification code for Google/Bing/Yandex/Pinterest/Baidu
  google_verification = ""
  bing_verification = ""
  yandex_verification = ""
  pinterest_verification = ""
  baidu_verification = ""

  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # LoveIt NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # LoveIt NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # LoveIt NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # LoveIt NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""


  [params.home]

    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "author.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      # title = ""
      # subtitle shown in home page
      subtitle = "Rants, Linux Tips, Infosec, Blue Team stuff"  # subtitle shown in home page
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  [params.cdn]                                       #### CSS and JS Files CDN
    fontawesome_free_css = ''                           # for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    animate_css = ''
    gitalk_css = ''
    gitalk_js = ''
    valine_js = ''
    jquery_js = ''
    lazysizes_js = ''
    smooth_scroll_js = ''
    katex_css = ''
    katex_js = ''
    katex_auto_render_js = ''
    mermaid_js = ''
    echarts_js = ''
    echarts_macarons_js = ''
    typeit_js = ''
    jquery_countdown_js = ''
    aplayer_css = ''
    aplayer_js = ''
    meting_js = ''

  [params.gravatar]                                      # Gravatar Info for preferred avatar in home page
    email = ""

  [params.social]                                        # Social Info in home page
    Gnupg = "/gpg/pub.txt"
    GitHub = "mosajjal"
    Linkedin = "mosajjal"
    Twitter = "_n0p_"
    #Instagram = "xxxx"
    #Email = "xxxx"
    Facebook = "mosajjal"
    Telegram = "mosajjal"
    Onion = "qa63pxzjgnnxgldbhwmilbr4ak2rbylf7wwqpz2papc5jyfi4sgiyeqd.onion"
    #Medium = "xxxx"
    Gitlab = "mosajjal"
    Dockerhub = "mosajjal"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    Reddit = "mosajjal"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    Mastodon = "@n0p"
    #Thingiverse = "xxxx"

  [params.share]                                         # Social Share Links in post page
    enable = true
    Twitter = true
    Facebook = true
    Reddit = true
    #Linkedin = true
    #Pinterest = true
    #HackerNews = true
    #Mix = true
    #Tumblr = true
    #VKontakte = true
    #Weibo = true

  [params.page.comment]
    enable = true
    # Disqus comment config
    [params.page.comment.disqus]
      # LoveIt NEW | 0.1.1
      enable = true
      # Disqus shortname to use Disqus in posts
      shortname = "n0p-me"

  [params.publisher]                                     # Publisher Info just for SEO
    name = "Ali Mosajjal"
    [params.publisher.logo]
      url = "author.jpg"
      width = 127
      height = 40

  [params.logo]                                          # Website Log Info just for SEO
    url = "author.jpg"
    width = 127
    height = 40

  [params.image]                                         # Website Image Info just for SEO
    url = "cover.png"
    width = 800
    height = 600

  [params.gitalk]                                        # Gittalk Comment Config (https://github.com/gitalk/gitalk)
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

  [params.valine]                                        # Valine Comment Config (https://github.com/xCss/Valine)
    enable = false
    appId = ""
    appKey = ""
    notify = false
    verify = true
    avatar = "mp"
    placeholder = "Your comment ..."
    visitor = true
    recordIP = true

[privacy]                                             #### Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]                                          #### Options to make hugo output .md files.
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]                              #### Options to make hugo output .md files.
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]                                             #### Options to make hugo output .md files.
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
